#!/usr/bin/env python3
"""Rewrite Caliptra's eight full-domain nonzero-byte bins exactly for Icarus.

The generated ``with ($countones(item[byte] > 0))`` predicate admits a value
when any bit in that byte is set. The equivalent wildcard bin is the union of
eight masks, each fixing one byte bit to 1 and leaving all other bits as
don't-cares. This source-hash-guarded overlay applies only to the disposable
copy made by ``soc_ifc_generated_empty_psprintf_overlay.py``.
"""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path
import subprocess


CALIPTRA_COMMIT = "49370266d12cb0c4a8f71b3a0ff7e54ba7d4866e"
SOURCE_RELATIVE = Path(
    "src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/"
    "interface_packages/soc_ifc_ctrl_pkg/src/"
    "soc_ifc_ctrl_transaction_coverage.svh"
)
SOURCE_SHA256 = "9e5e6f540303af5302315afca7ea8323a3ef883024aa11a0410f83f24c1fbfaf"
OVERLAY_RELATIVE = Path(
    "soc_ifc_ctrl_pkg/src/soc_ifc_ctrl_transaction_coverage.svh"
)
BIN_RE = re.compile(
    r"^(\s*)bins byte_(\d)\s*=\s*\{\[0:\$\]\}\s+with\s+"
    r"\(\$countones\(item\[\s*(\d+)\s*:\s*(\d+)\s*\]\s*>\s*0\)\);\s*$",
    re.MULTILINE,
)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def wildcard_bin(indent: str, index: int) -> str:
    patterns = []
    for bit_in_byte in range(8):
        absolute_bit = index * 8 + bit_in_byte
        bits = ["?"] * 64
        bits[63 - absolute_bit] = "1"
        patterns.append("64'b" + "".join(bits))
    rendered = ",\n".join(indent + "  " + pattern for pattern in patterns)
    return f"{indent}wildcard bins byte_{index} = {{\n{rendered}\n{indent}}};"


def transform(source: bytes) -> bytes:
    if sha256(source) != SOURCE_SHA256:
        raise SystemExit("refusing unreviewed SoC-IFC control coverage source")
    text = source.decode("utf-8")
    matches = list(BIN_RE.finditer(text))
    if len(matches) != 8:
        raise SystemExit(f"expected eight generated byte bins, found {len(matches)}")
    indices = {int(match.group(2)) for match in matches}
    if indices != set(range(8)):
        raise SystemExit(f"unexpected generated byte-bin indices: {sorted(indices)}")

    for match in reversed(matches):
        indent, name_index, high_text, low_text = match.groups()
        index = int(name_index)
        high, low = int(high_text), int(low_text)
        if (index, high, low) != (index, index * 8 + 7, index * 8):
            raise SystemExit(
                f"byte_{index} has unexpected slice [{high}:{low}]"
            )
        replacement = wildcard_bin(indent, index)
        text = text[:match.start()] + replacement + text[match.end():]

    if "with ($countones(item[" in text:
        raise SystemExit("a generated full-domain byte filter was left unchanged")
    return text.encode("utf-8")


def apply_overlay(caliptra_root: Path, package_overlay: Path) -> tuple[str, str]:
    caliptra_root = caliptra_root.resolve()
    package_overlay = package_overlay.resolve()
    if package_overlay == caliptra_root or caliptra_root in package_overlay.parents:
        raise SystemExit("overlay output must be outside the pinned Caliptra tree")

    commit = subprocess.run(
        ["git", "-C", str(caliptra_root), "rev-parse", "HEAD"],
        text=True,
        capture_output=True,
        check=False,
    )
    if commit.returncode or commit.stdout.strip() != CALIPTRA_COMMIT:
        raise SystemExit(
            f"expected Caliptra {CALIPTRA_COMMIT}, got "
            f"{commit.stdout.strip() or 'unavailable'}"
        )

    source = caliptra_root / SOURCE_RELATIVE
    target = package_overlay / OVERLAY_RELATIVE
    original = source.read_bytes()
    if sha256(original) != SOURCE_SHA256:
        raise SystemExit(f"pinned coverage source hash mismatch: {source}")
    if not target.is_file() or sha256(target.read_bytes()) != SOURCE_SHA256:
        raise SystemExit(
            f"expected an unmodified disposable package copy at {target}"
        )

    output = transform(original)
    target.write_bytes(output)
    return sha256(original), sha256(output)


def main() -> None:
    repo = Path(__file__).resolve().parents[4]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--caliptra-root",
        type=Path,
        default=repo.parent / "caliptra-rtl",
        help="pinned Caliptra checkout (default: sibling caliptra-rtl)",
    )
    parser.add_argument(
        "--package-overlay",
        required=True,
        type=Path,
        help="existing disposable package tree made by the psprintf overlay",
    )
    args = parser.parse_args()
    before, after = apply_overlay(args.caliptra_root, args.package_overlay)
    print(f"generated source SHA-256: {before}")
    print(f"wildcard overlay SHA-256: {after}")
    print("rewrote eight bins; each byte predicate is represented exactly")


if __name__ == "__main__":
    main()
