// SPDX-License-Identifier: Apache-2.0
// Reuse the independent target and transaction sequence; corrupt only its pins.
module tb_four_state;
  tb_axi4 test();
  reg [8*16-1:0] signal_name;
  logic unknown_bit;
  logic [31:0] unknown_word;
  logic [7:0] unknown_id;
  logic [1:0] unknown_resp;
  initial begin
    unknown_bit = $test$plusargs("Z") ? 1'bz : 1'bx;
    unknown_word = {32{unknown_bit}};
    unknown_id = {8{unknown_bit}};
    unknown_resp = {2{unknown_bit}};
    if (!$value$plusargs("SIGNAL=%s", signal_name)) $fatal(1,"missing SIGNAL");
    case (signal_name)
      "CHECK": test.check(unknown_bit,"unknown test condition rejected");
      "AWREADY": begin wait(test.awvalid); force test.awready=unknown_bit; end
      "WREADY": begin wait(test.wvalid); force test.wready=unknown_bit; end
      "ARREADY": begin wait(test.arvalid); force test.arready=unknown_bit; end
      "BVALID": begin wait(test.bready); force test.bvalid=unknown_bit; end
      "RVALID": begin wait(test.rready); force test.rvalid=unknown_bit; end
      "BRESP": begin wait(test.bready); force test.bresp=unknown_resp; end
      "RRESP": begin wait(test.rready); force test.rresp=unknown_resp; end
      "BID": begin wait(test.bready); force test.bid=unknown_id; end
      "RID": begin wait(test.rready); force test.rid=unknown_id; end
      "RLAST": begin wait(test.rready); force test.rlast=unknown_bit; end
      "RDATA": begin wait(test.rready); force test.rdata=unknown_word; end
      "IDLE_PAYLOAD": begin
        force test.bresp=2'bxx; force test.bid=8'hxx;
        force test.rresp=2'bxx; force test.rid=8'hxx;
        force test.rlast=1'bx; force test.rdata=32'hxxxxxxxx;
        // Release before the first response is generated by the real target.
        wait(test.awvalid);
        release test.bresp; release test.bid;
        wait(test.arvalid);
        release test.rresp; release test.rid;
        release test.rlast; release test.rdata;
      end
      "ERROR_RDATA": begin
        wait(test.inject_error && test.rready);
        force test.rdata=32'hxxxxxxxx;
      end
      default: $fatal(1,"unrecognized SIGNAL");
    endcase
    $display("INJECTED: %0s", signal_name);
  end
  initial begin
    #10000; $fatal(1,"four-state watchdog expired");
  end
endmodule
