// SPDX-License-Identifier: Apache-2.0
// Connects the standalone Caliptra DMA target to Caliptra's axi_if interface.
module axi4_caliptra_dma_if_subordinate #(
  parameter integer ADDR_WIDTH = 48,
  parameter integer DATA_WIDTH = 32,
  parameter integer ID_WIDTH = 8,
  parameter integer USER_WIDTH = 32,
  parameter [ADDR_WIDTH-1:0] SRAM_BASE_ADDR = 48'h0001_2344_0000,
  parameter integer SRAM_BYTES = 262144,
  parameter [ADDR_WIDTH-1:0] FIFO_BASE_ADDR = 48'h0000_fa57_0000,
  parameter integer FIFO_CAPACITY_BYTES = 65536,
  parameter integer DECODE_LOW_BITS = $clog2(SRAM_BYTES),
  parameter integer RECOVERY_MODE = 0,
  parameter integer DMA_BLOCK_COUNT = 100
) (
  input wire ACLK,
  input wire ARESETn,
  axi_if.w_sub m_axi_w_if,
  axi_if.r_sub m_axi_r_if,
  input wire fifo_clear,
  input wire auto_fifo_push,
  input wire auto_fifo_pop,
  input wire use_dma_gen_sequence,
  input wire dma_gen_done,
  input wire [DMA_BLOCK_COUNT*12-1:0] dma_gen_block_size_bytes,
  input wire en_recovery_emulation,
  input wire [31:0] recovery_threshold_words,
  input wire [31:0] recovery_block_words,
  input wire inject_error,
  input wire stall_sram_aw,
  input wire stall_sram_w,
  input wire stall_sram_b,
  input wire stall_sram_ar,
  input wire stall_sram_r,
  input wire stall_fifo_aw,
  input wire stall_fifo_w,
  input wire stall_fifo_b,
  input wire stall_fifo_ar,
  input wire stall_fifo_r,
  output wire [31:0] fifo_level,
  output wire fifo_push_event,
  output wire fifo_pop_event,
  output wire recovery_data_avail
);
  axi4_caliptra_dma_subordinate #(
    .ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH),
    .ID_WIDTH(ID_WIDTH), .USER_WIDTH(USER_WIDTH),
    .SRAM_BASE_ADDR(SRAM_BASE_ADDR), .SRAM_BYTES(SRAM_BYTES),
    .FIFO_BASE_ADDR(FIFO_BASE_ADDR),
    .FIFO_CAPACITY_BYTES(FIFO_CAPACITY_BYTES),
    .DECODE_LOW_BITS(DECODE_LOW_BITS), .RECOVERY_MODE(RECOVERY_MODE),
    .DMA_BLOCK_COUNT(DMA_BLOCK_COUNT)
  ) bfm (
    .ACLK(ACLK),
    .ARESETn(ARESETn),
    .fifo_clear(fifo_clear),
    .auto_fifo_push(auto_fifo_push),
    .auto_fifo_pop(auto_fifo_pop),
    .use_dma_gen_sequence(use_dma_gen_sequence),
    .dma_gen_done(dma_gen_done),
    .dma_gen_block_size_bytes(dma_gen_block_size_bytes),
    .en_recovery_emulation(en_recovery_emulation),
    .recovery_threshold_words(recovery_threshold_words),
    .recovery_block_words(recovery_block_words),
    .inject_error(inject_error),
    .stall_sram_aw(stall_sram_aw),
    .stall_sram_w(stall_sram_w),
    .stall_sram_b(stall_sram_b),
    .stall_sram_ar(stall_sram_ar),
    .stall_sram_r(stall_sram_r),
    .stall_fifo_aw(stall_fifo_aw),
    .stall_fifo_w(stall_fifo_w),
    .stall_fifo_b(stall_fifo_b),
    .stall_fifo_ar(stall_fifo_ar),
    .stall_fifo_r(stall_fifo_r),
    .fifo_level(fifo_level),
    .fifo_push_event(fifo_push_event),
    .fifo_pop_event(fifo_pop_event),
    .recovery_data_avail(recovery_data_avail),
    .AWID(m_axi_w_if.awid),
    .AWADDR(m_axi_w_if.awaddr),
    .AWLEN(m_axi_w_if.awlen),
    .AWSIZE(m_axi_w_if.awsize),
    .AWBURST(m_axi_w_if.awburst),
    .AWLOCK(m_axi_w_if.awlock),
    .AWUSER(m_axi_w_if.awuser),
    .AWVALID(m_axi_w_if.awvalid),
    .AWREADY(m_axi_w_if.awready),
    .WDATA(m_axi_w_if.wdata),
    .WSTRB(m_axi_w_if.wstrb),
    .WUSER(m_axi_w_if.wuser),
    .WLAST(m_axi_w_if.wlast),
    .WVALID(m_axi_w_if.wvalid),
    .WREADY(m_axi_w_if.wready),
    .BID(m_axi_w_if.bid),
    .BRESP(m_axi_w_if.bresp),
    .BUSER(m_axi_w_if.buser),
    .BVALID(m_axi_w_if.bvalid),
    .BREADY(m_axi_w_if.bready),
    .ARID(m_axi_r_if.arid),
    .ARADDR(m_axi_r_if.araddr),
    .ARLEN(m_axi_r_if.arlen),
    .ARSIZE(m_axi_r_if.arsize),
    .ARBURST(m_axi_r_if.arburst),
    .ARLOCK(m_axi_r_if.arlock),
    .ARUSER(m_axi_r_if.aruser),
    .ARVALID(m_axi_r_if.arvalid),
    .ARREADY(m_axi_r_if.arready),
    .RID(m_axi_r_if.rid),
    .RDATA(m_axi_r_if.rdata),
    .RRESP(m_axi_r_if.rresp),
    .RUSER(m_axi_r_if.ruser),
    .RLAST(m_axi_r_if.rlast),
    .RVALID(m_axi_r_if.rvalid),
    .RREADY(m_axi_r_if.rready)
  );
endmodule
