+incdir+/private/tmp/bfm-work-install/lib/ivl/uvm/src
+incdir+dv/caliptra_bfm/uvm
+incdir+dv/caliptra_bfm/uvmf_lite
+incdir+dv/caliptra_bfm/ahb_lite
+incdir+dv/caliptra_bfm/axi
+incdir+/private/tmp/bfm-hostpkgs-ctor-overlay2-20261004
+incdir+/private/tmp/bfm-hostpkgs-ctor-overlay2-20261004/src
+incdir+/private/tmp/bfm-hostpkgs-ctor-overlay2-20261004/registers
+incdir+/private/tmp/bfm-hostpkgs-ctor-overlay2-20261004/sequences/mbox/soc_ifc
+incdir+/private/tmp/caliptra-soc-ifc-hostpkg-8hdd96u0/include
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/integration/rtl
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/integration/rtl/caliptra_reg
+incdir+/private/tmp/bfm-hostpkgs-rtl-overlay-probe-20261004
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/axi/rtl
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/keyvault/rtl
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/libs/aaxi_uvm
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/project_benches/soc_ifc/tb/parameters
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/integration/rtl/config_defines.svh
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/integration/rtl/caliptra_reg/caliptra_reg_defines.svh
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/integration/rtl/caliptra_reg/caliptra_reg_field_defines.svh
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/axi/rtl/axi_pkg.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl/soc_ifc_pkg.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl/mbox_pkg.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl/mbox_csr_pkg.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl/sha512_acc_csr_pkg.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl/soc_ifc_reg_pkg.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/axi/rtl/axi_dma_reg_pkg.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/keyvault/rtl/kv_defines_pkg.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/axi/rtl/axi_dma_reg_uvm.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl/mbox_csr_uvm.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl/sha512_acc_csr_uvm.sv
/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/soc_ifc/rtl/soc_ifc_reg_uvm.sv
dv/caliptra_bfm/uvm/axi4_caliptra_record_if.sv
dv/caliptra_bfm/uvm/axi4_caliptra_master_cmd_if.sv
dv/caliptra_bfm/uvm/ahb_lite_caliptra_record_if.sv
dv/caliptra_bfm/uvm/ahb_lite_caliptra_pin_monitor_adapter.sv
dv/caliptra_bfm/uvm/ahb_lite_caliptra_master_cmd_if.sv
dv/caliptra_bfm/uvm/caliptra_ahb_mvc_compat_pkg.sv
dv/caliptra_bfm/uvm/aaxi_pkg_compat.sv
dv/caliptra_bfm/uvm/aaxi_intf_compat.sv
dv/caliptra_bfm/uvm/aaxi_generated_namespace_compat.sv
dv/caliptra_bfm/uvm/caliptra_aaxi_compat_pkg.sv
dv/caliptra_bfm/uvm/axi4_caliptra_uvm_pkg.sv
dv/caliptra_bfm/uvm/caliptra_aaxi_uvmf_compat_pkg.sv
dv/caliptra_bfm/uvm/ahb_lite_caliptra_uvm_pkg.sv
dv/caliptra_bfm/uvm/pv_caliptra_master_cmd_if.sv
dv/caliptra_bfm/uvm/pv_caliptra_uvm_pkg.sv
dv/caliptra_bfm/uvmf_lite/uvmf_base_pkg_hdl.sv
dv/caliptra_bfm/uvmf_lite/uvmf_base_pkg.sv
dv/caliptra_bfm/uvm/caliptra_ahb_qvip_compat_pkg.sv
dv/caliptra_bfm/axi/axi4_caliptra_master.sv
dv/caliptra_bfm/axi/axi4_caliptra_memory_subordinate.sv
dv/caliptra_bfm/axi/axi4_caliptra_fifo_subordinate.sv
dv/caliptra_bfm/axi/axi4_caliptra_recovery_sequence.sv
dv/caliptra_bfm/axi/axi4_caliptra_recovery_avail.sv
dv/caliptra_bfm/axi/axi4_caliptra_dma_subordinate.sv
dv/caliptra_bfm/axi/axi4_caliptra_transaction_monitor.sv
dv/caliptra_bfm/ahb_lite/ahb_lite_caliptra_master.sv
dv/caliptra_bfm/ahb_lite/ahb_lite_caliptra_memory_subordinate.sv
dv/caliptra_bfm/ahb_lite/ahb_lite_caliptra_monitor.sv
dv/caliptra_bfm/uvm/axi4_caliptra_uvm_master_proxy.sv
dv/caliptra_bfm/uvm/ahb_lite_caliptra_uvm_master_proxy.sv
dv/caliptra_bfm/uvm/ahb_lite_caliptra_qvip_hdl.sv
dv/caliptra_bfm/axi/axi4_caliptra_checker.sv
dv/caliptra_bfm/uvm/aaxi_monitor_wrapper_compat.sv
/private/tmp/bfm-hostpkgs-ctor-overlay2-20261004/registers/soc_ifc_reg_model_top_pkg.sv
+incdir+/Users/danielellerbrock/projects/iverilog_uvm/caliptra-rtl/src/libs/rtl
+define+CLP_OBF_KEY_DWORDS=8
+define+CLP_OBF_FE_DWORDS=8
+define+CLP_OBF_UDS_DWORDS=16

/private/tmp/caliptra-soc-ifc-hostpkg-8hdd96u0/hostpkg_compile_top.sv
