// SPDX-License-Identifier: Apache-2.0
// Connects Caliptra's axi_if DMA pins to the native UVM record adapter.
module axi4_caliptra_dma_if_monitor (
  input wire ACLK,
  input wire ARESETn,
  axi_if.w_sub m_axi_w_if,
  axi_if.r_sub m_axi_r_if,
  axi4_caliptra_record_if record_if
);
  assign record_if.ARESETn = ARESETn;

  axi4_caliptra_checker #(
    .ADDR_WIDTH($bits(m_axi_w_if.awaddr)),
    .DATA_WIDTH($bits(m_axi_w_if.wdata)),
    .ID_WIDTH($bits(m_axi_w_if.awid)),
    .USER_WIDTH($bits(m_axi_w_if.awuser))
  ) profile_checker (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .AWID(m_axi_w_if.awid), .AWADDR(m_axi_w_if.awaddr),
    .AWLEN(m_axi_w_if.awlen), .AWSIZE(m_axi_w_if.awsize),
    .AWBURST(m_axi_w_if.awburst), .AWLOCK(m_axi_w_if.awlock),
    .AWUSER(m_axi_w_if.awuser), .AWVALID(m_axi_w_if.awvalid),
    .AWREADY(m_axi_w_if.awready), .WDATA(m_axi_w_if.wdata),
    .WSTRB(m_axi_w_if.wstrb), .WUSER(m_axi_w_if.wuser),
    .WLAST(m_axi_w_if.wlast), .WVALID(m_axi_w_if.wvalid),
    .WREADY(m_axi_w_if.wready), .BID(m_axi_w_if.bid),
    .BRESP(m_axi_w_if.bresp), .BUSER(m_axi_w_if.buser),
    .BVALID(m_axi_w_if.bvalid), .BREADY(m_axi_w_if.bready),
    .ARID(m_axi_r_if.arid), .ARADDR(m_axi_r_if.araddr),
    .ARLEN(m_axi_r_if.arlen), .ARSIZE(m_axi_r_if.arsize),
    .ARBURST(m_axi_r_if.arburst), .ARLOCK(m_axi_r_if.arlock),
    .ARUSER(m_axi_r_if.aruser), .ARVALID(m_axi_r_if.arvalid),
    .ARREADY(m_axi_r_if.arready), .RID(m_axi_r_if.rid),
    .RDATA(m_axi_r_if.rdata), .RRESP(m_axi_r_if.rresp),
    .RUSER(m_axi_r_if.ruser), .RLAST(m_axi_r_if.rlast),
    .RVALID(m_axi_r_if.rvalid), .RREADY(m_axi_r_if.rready)
  );

  axi4_caliptra_monitor #(
    .ADDR_WIDTH($bits(m_axi_w_if.awaddr)),
    .DATA_WIDTH($bits(m_axi_w_if.wdata)),
    .ID_WIDTH($bits(m_axi_w_if.awid)),
    .USER_WIDTH($bits(m_axi_w_if.awuser))
  ) channel_monitor (
    .ACLK(ACLK), .ARESETn(ARESETn),
    .AWID(m_axi_w_if.awid), .AWADDR(m_axi_w_if.awaddr),
    .AWLEN(m_axi_w_if.awlen), .AWSIZE(m_axi_w_if.awsize),
    .AWBURST(m_axi_w_if.awburst), .AWLOCK(m_axi_w_if.awlock),
    .AWUSER(m_axi_w_if.awuser), .AWVALID(m_axi_w_if.awvalid),
    .AWREADY(m_axi_w_if.awready), .WDATA(m_axi_w_if.wdata),
    .WSTRB(m_axi_w_if.wstrb), .WUSER(m_axi_w_if.wuser),
    .WLAST(m_axi_w_if.wlast), .WVALID(m_axi_w_if.wvalid),
    .WREADY(m_axi_w_if.wready), .BID(m_axi_w_if.bid),
    .BRESP(m_axi_w_if.bresp), .BUSER(m_axi_w_if.buser),
    .BVALID(m_axi_w_if.bvalid), .BREADY(m_axi_w_if.bready),
    .ARID(m_axi_r_if.arid), .ARADDR(m_axi_r_if.araddr),
    .ARLEN(m_axi_r_if.arlen), .ARSIZE(m_axi_r_if.arsize),
    .ARBURST(m_axi_r_if.arburst), .ARLOCK(m_axi_r_if.arlock),
    .ARUSER(m_axi_r_if.aruser), .ARVALID(m_axi_r_if.arvalid),
    .ARREADY(m_axi_r_if.arready), .RID(m_axi_r_if.rid),
    .RDATA(m_axi_r_if.rdata), .RRESP(m_axi_r_if.rresp),
    .RUSER(m_axi_r_if.ruser), .RLAST(m_axi_r_if.rlast),
    .RVALID(m_axi_r_if.rvalid), .RREADY(m_axi_r_if.rready),
    .aw_fire(record_if.aw_fire), .aw_record(record_if.aw_record),
    .w_fire(record_if.w_fire), .w_record(record_if.w_record),
    .b_fire(record_if.b_fire), .b_record(record_if.b_record),
    .ar_fire(record_if.ar_fire), .ar_record(record_if.ar_record),
    .r_fire(record_if.r_fire), .r_record(record_if.r_record),
    .cycle_count(record_if.channel_cycle),
    .aw_count(record_if.aw_count), .w_count(record_if.w_count),
    .b_count(record_if.b_count), .ar_count(record_if.ar_count),
    .r_count(record_if.r_count),
    .aw_stall_cycles(record_if.aw_stall_cycles),
    .w_stall_cycles(record_if.w_stall_cycles),
    .b_stall_cycles(record_if.b_stall_cycles),
    .ar_stall_cycles(record_if.ar_stall_cycles),
    .r_stall_cycles(record_if.r_stall_cycles)
  );

  axi4_caliptra_transaction_monitor monitor (
    .ACLK(ACLK),
    .ARESETn(ARESETn),
    .AWID(m_axi_w_if.awid),
    .AWADDR(m_axi_w_if.awaddr),
    .AWLEN(m_axi_w_if.awlen),
    .AWSIZE(m_axi_w_if.awsize),
    .AWBURST(m_axi_w_if.awburst),
    .AWLOCK(m_axi_w_if.awlock),
    .AWUSER(m_axi_w_if.awuser),
    .AWVALID(m_axi_w_if.awvalid),
    .AWREADY(m_axi_w_if.awready),
    .WDATA(m_axi_w_if.wdata),
    .WSTRB(m_axi_w_if.wstrb),
    .WUSER(m_axi_w_if.wuser),
    .WLAST(m_axi_w_if.wlast),
    .WVALID(m_axi_w_if.wvalid),
    .WREADY(m_axi_w_if.wready),
    .BID(m_axi_w_if.bid),
    .BRESP(m_axi_w_if.bresp),
    .BUSER(m_axi_w_if.buser),
    .BVALID(m_axi_w_if.bvalid),
    .BREADY(m_axi_w_if.bready),
    .ARID(m_axi_r_if.arid),
    .ARADDR(m_axi_r_if.araddr),
    .ARLEN(m_axi_r_if.arlen),
    .ARSIZE(m_axi_r_if.arsize),
    .ARBURST(m_axi_r_if.arburst),
    .ARLOCK(m_axi_r_if.arlock),
    .ARUSER(m_axi_r_if.aruser),
    .ARVALID(m_axi_r_if.arvalid),
    .ARREADY(m_axi_r_if.arready),
    .RID(m_axi_r_if.rid),
    .RDATA(m_axi_r_if.rdata),
    .RRESP(m_axi_r_if.rresp),
    .RUSER(m_axi_r_if.ruser),
    .RLAST(m_axi_r_if.rlast),
    .RVALID(m_axi_r_if.rvalid),
    .RREADY(m_axi_r_if.rready),
    .cycle_count(),
    .write_complete(record_if.write_complete),
    .write_request_complete(record_if.write_request_complete),
    .write_request_error(record_if.write_request_error),
    .write_request_status(record_if.write_request_status),
    .write_request_id(record_if.write_request_id),
    .write_request_addr(record_if.write_request_addr),
    .write_request_len(record_if.write_request_len),
    .write_request_size(record_if.write_request_size),
    .write_request_burst(record_if.write_request_burst),
    .write_request_lock(record_if.write_request_lock),
    .write_request_awuser(record_if.write_request_awuser),
    .write_request_beat_count(record_if.write_request_beat_count),
    .write_request_data(record_if.write_request_data),
    .write_request_strb(record_if.write_request_strb),
    .write_request_wuser(record_if.write_request_wuser),
    .write_request_last_mask(record_if.write_request_last_mask),
    .write_error(record_if.write_error),
    .write_error_code(record_if.write_error_code),
    .write_status(record_if.write_status),
    .write_cycle(),
    .write_id(record_if.write_id),
    .write_addr(record_if.write_addr),
    .write_len(record_if.write_len),
    .write_size(record_if.write_size),
    .write_burst(record_if.write_burst),
    .write_lock(record_if.write_lock),
    .write_awuser(record_if.write_awuser),
    .write_beat_count(record_if.write_beat_count),
    .write_data(record_if.write_data),
    .write_strb(record_if.write_strb),
    .write_wuser(record_if.write_wuser),
    .write_last_mask(record_if.write_last_mask),
    .write_response_id(record_if.write_response_id),
    .write_response(record_if.write_response),
    .write_buser(record_if.write_buser),
    .read_complete(record_if.read_complete),
    .read_error(record_if.read_error),
    .read_error_code(record_if.read_error_code),
    .read_status(record_if.read_status),
    .read_cycle(),
    .read_id(record_if.read_id),
    .read_addr(record_if.read_addr),
    .read_len(record_if.read_len),
    .read_size(record_if.read_size),
    .read_burst(record_if.read_burst),
    .read_lock(record_if.read_lock),
    .read_aruser(record_if.read_aruser),
    .read_beat_count(record_if.read_beat_count),
    .read_data(record_if.read_data),
    .read_resp(record_if.read_resp),
    .read_ruser(record_if.read_ruser),
    .read_last_mask(record_if.read_last_mask)
  );
endmodule
